services:
  - type: web
    name: velox-host
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node .
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
